name: CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc curl texlive-xetex

      - name: Fetch Markdown Styling
        run: curl -L https://raw.githubusercontent.com/sindresorhus/github-markdown-css/main/github-markdown.css -o style.css

      - name: Generate Resume PDF
        run: |
          pandoc resume.md \
            -o resume.pdf \
            --pdf-engine=xelatex \
            --css=style.css \
            -V geometry:margin=0.5in

      - name: Generate Resume HTML
        run: |
          pandoc resume.md \
            -o resume.html \
            -s --css=style.css \

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './'  # Upload both resume.pdf and resume.html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
